#!/bin/bash -e

# DEPENDS:
# * mountpoint
# * mount
# * mkdir
# * mktemp
# * runuser
# * sudo

# VARIABLES:
# PWD=    (build directory)

export PATH=/usr/sbin:/sbin:/usr/bin:/bin
export TMPDIR=/tmp
[ -n "$1" ] || exit 0

if [ $(id -u) != 0 ] ; then
    export ENDUSER=$(id -un)
    exec sudo -E -- "${BASH_SOURCE[0]}" "$@"
fi

exec unshare -m -- bash -ec '
[ -n "$ENDUSER" ] || ENDUSER="$USER"
ENDUID=$(id -u "$ENDUSER")
ENDGID=$(id -g "$ENDUSER")
echo Running "$@" under modified environment. >&2
mountpoint -q "$TMPDIR" && umount "$TMPDIR" || true
mkdir -p ./tmp
chown "$ENDUID"."$ENDGID" ./tmp
chmod 0700 ./tmp
mount --bind ./tmp "$TMPDIR"
tmpd="$TMPDIR/build-android-$ENDUID"
mkdir "$tmpd"
chmod 0700 "$tmpd"
chown "$ENDUID"."$ENDGID" "$tmpd"
mount --bind "$PWD" "$tmpd"
cd "$tmpd"
exec runuser -p -u "$ENDUSER" -- "$@"
' -- "$@"
