#!/bin/bash -e

# DEPENDS:
# * mountpoint
# * mount
# * mkdir
# * mktemp
# * runuser
# * sudo

# FIXME: make it impossible for the script to create
# directories where root has write access but the
# calling user does not.

# VARIABLES:
# PWD=    (build directory)

export PATH=/usr/sbin:/sbin:/usr/bin:/bin
[ -n "$1" ] || exit 0

[ -n "$TMPDIR" ] && { export TMPDIR ; } || { export TMPDIR="/tmp" ; }

if [ "$BINDMOUNT_PREINITIALIZED" != "true" ] ; then
    export ENDUSER=$(id -un)
    export ENDTMPDIR=$(mktemp -d "$TMPDIR/build-android-$(id -un)-XXXXXXX")
    mkdir -p "$ENDTMPDIR"
    chmod 700 "$ENDTMPDIR"
    mkdir -p "$ENDTMPDIR"/cwd
    chmod 700 "$ENDTMPDIR"/cwd
    export BINDMOUNT_PREINITIALIZED=true
    exec sudo -E -- "${BASH_SOURCE[0]}" "$@"
fi

exec unshare -m -- bash -ec '
echo "=== Running $@ under modified environment ===" >&2
echo "=== $ENDTMPDIR/tmp will be bind-mounted to /tmp ===" >&2
echo "=== $PWD will be bind-mounted to $ENDTMPDIR/cwd and appear as /tmp/cwd ===" >&2
echo "=== Will CD into $ENDTMPDIR/cwd, replacing $PWD as working directory ===" >&2
mount --bind "$ENDTMPDIR" "/tmp"
mount --bind "$PWD" "/tmp/cwd"
export TMPDIR=/tmp
cd "/tmp/cwd"
exec runuser -p -u "$ENDUSER" -- "$@"
' -- "$@"
