#!/bin/bash -e

# VARIABLES:
# BUILD_DIR=
# ANDROID_BUILD_TAG=
# ANDROID_BUILD_SPEC=

set -o pipefail

# It is necessary to do a full rebuild when the parameters have changed
# and those parameters are within the contents of $this.
# It is conversely not necessary to do a full rebuild when the parameters
# remain the same, but what is being retried is a prior temporarily-failed
# build.  Thus we perform this comparison before the build, not using
# values from after the build.

this="$ANDROID_BUILD_SPEC-$ANDROID_BUILD_TAG"
echo "$this" > this-build-inputs.txt
old=$(cat last-build-inputs.txt || true)
if [ "$this" != "$old" ] ; then
    echo Full rebuild
    rm -rfv src/out/ | (
        f=0
        while read -r line
        do
            f=$(( $f + 1 ))
            if [ $(( ($f -1) / 1000 )) != $(( ($f) / 1000 )) ]
            then
                echo "$f files removed; last deleted: $line" >&2
            fi
        done
    )
    mkdir -p src/out/
else
    echo Incremental build
fi
mv -f this-build-inputs.txt last-build-inputs.txt
