#!/bin/bash -xe

# DEPENDS:
# * rsync
# * tr

# VARIABLES:
# PRODUCT_NAME=    (name of device)
# ANDROID_BUILD_ID=        (first portion of ANDROID_BUILD_TAG obtained from Copperhead builds feed)

export DISPLAY=

# Obtain Google official images
cd src
if [[ $PRODUCT_NAME == hikey* ]]; then
  true
else
  bash -x vendor/android-prepare-vendor/execute-all.sh -d "$PRODUCT_NAME" -b "$ANDROID_BUILD_ID" -o vendor/android-prepare-vendor
  lowerbuildid=$(echo "$ANDROID_BUILD_ID" | tr '[:upper:]' '[:lower:]')
  mkdir -p vendor/google_devices
  rsync -a --delete \
     vendor/android-prepare-vendor/"$PRODUCT_NAME"/"$lowerbuildid"/vendor/google_devices/"$PRODUCT_NAME"/ \
     vendor/google_devices/"$PRODUCT_NAME"/
  if [[ $PRODUCT_NAME == sailfish ]]; then
     rsync -a --delete \
        vendor/android-prepare-vendor/"$PRODUCT_NAME"/"$lowerbuildid"/vendor/google_devices/marlin/ \
        vendor/google_devices/marlin/
  fi
  # Clear out anything that was unpacked under android-prepare-vendor.
  rm -rf vendor/android-prepare-vendor/*/*/vendor*
fi
