#!/bin/bash -xe

# DEPENDS:
# * rsync

# VARIABLES:
# PWD=                      (job directory, usually parent of workspace directory)
# RELEASE_UPLOAD_ADDRESS=   (user@host:/path/to/folder for SSH copy)
# CHANNEL_NAME=

if [ -z "$CHANNEL_NAME" ] ; then exit ; fi
if [ -z "$RELEASE_UPLOAD_ADDRESS" ] ; then exit ; fi

cd builds/"$BUILD_NUMBER"/archive/out/
rsync -a -- */* "$RELEASE_UPLOAD_ADDRESS"/
