#!/bin/bash -e

# DEPENDS:
# * sudo
# * util-linux

# VARIABLES:
# PRODUCT_NAME=
# ANDROID_BUILD_SPEC=

# export OUT_DIR="$PWD/out"

cd src
source script/copperhead.sh
choosecombo "$BUILD_TYPE" aosp_"$PRODUCT_NAME" "$BUILD_VARIANT"
set -x

rm -rf out/release-*
bash -xe script/release.sh "$PRODUCT_NAME"

# Rename file to match channel metadata.
mv out/release-"$PRODUCT_NAME"-"$BUILD_NUMBER" out/release-"$ANDROID_BUILD_SPEC"-"$ANDROID_BUILD_TAG"
# Obtain the build date UTC timestamp, which the channel metadata must have in order for the update to validate.
# See src/packages/apps/Updater/src/co/copperhead/updater/Service.java for more information.
NOW=$(grep ^ro.build.date.utc= out/target/product/"$PRODUCT_NAME"/system/build.prop | awk -F = ' { print $2 } ')
# Obtain the version, which the channel metadata must have.
VERSION=$(grep -Po "export BUILD_ID=\K.+" build/core/build_id.mk | tr '[:upper:]' '[:lower:]')
# Create release channel metadata information.
echo "$BUILD_NUMBER $NOW $ANDROID_BUILD_ID" > out/release-"$ANDROID_BUILD_SPEC"-"$ANDROID_BUILD_TAG"/"$PRODUCT_NAME-$CHANNEL_NAME"
