#!/bin/bash -xe

# DEPENDS:
# * sudo
# * util-linux

# VARIABLES:
SWAP_SIZE_MB=16384

test -f swapfile || {
  echo "Making swapfile of $SWAP_SIZE_MB" >&2
  dd if=/dev/zero of=swapfile bs=1M count="$SWAP_SIZE_MB"
  sudo mkswap swapfile
}
sudo swapon -s | egrep -q '/swapfile\s+file' || {
  echo "Activating swapfile" >&2
  sudo chown root.root swapfile
  sudo chmod 0600 swapfile
  sudo swapon swapfile
}
